FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
ENV ASPNETCORE_URLS=http://+:5000
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["./TestMVC.csproj", "./"]
RUN dotnet restore "TestMVC.csproj"
COPY . .
RUN dotnet build "./TestMVC.csproj" -c Release -o /app/build
FROM build AS publish
RUN dotnet publish "./TestMVC.csproj" -c Release -o /app/publish
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "/app/TestMVC.dll"]
