version: '3.7'
services:
 projet:
  build:
   context : ./TestMVC/
   dockerfile : dockerfile
  container_name: deploy_project
  expose:
   - "5000"
  restart : always
  depends_on:
   - nginx

 nginx:
  image: nginx:alpine
  container_name: nginx_deploy_project
  volumes:
   - "./nginx.conf:/etc/nginx/nginx.d"
  ports:
   - "4001:80"
  restart : always

